# Merge Amplicon Datasets by ASV sequence

Join "Flyer2018" and "RREAS2018" datasets for 18S, COI, and 12S

In [3]:
import pandas as pd
# import glob

### Set Locations

In [22]:
directory = "./Data/filtered_data/"
markers = ['18S', 'COI', '12S']
prefixes = ['RREAS2018', 'Flyer2018']

## Import Data

# 18S data

### RREAS2018

In [25]:
marker = '18S'
prefix = 'RREAS2018'

# otu table
file = prefix +'_'+marker+'_otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))

# taxa table
file = prefix +'_'+marker+'_taxa_filtered.csv'
df = pd.read_csv(directory+file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
taxa_all = df.copy()
print('Number ASVs:', len(df.index))

# sequence table
file = prefix +'_'+marker+'_seq_filtered.csv'
df = pd.read_csv(directory +file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
seq_all = df.copy()
print('Number ASVs:', len(df.index))

df.head()

./Data/filtered_data/RREAS2018_18S_otu_filtered.csv
Number ASVs: 7497
Number ASVs: 7497
Number ASVs: 7497

                                                sequence
ASV
ASV_1  GCTACTACCGATTGAACATTTTAGTGAGGTCCTCGGACTGTGAGCC...
ASV_2  GCTACTACCGATTGAACGTTTTAGTGAGGTCCTCGGACTGTTTGCC...
ASV_3  GCTACTACCGATTGGATGGTTTAGTGAGGTCCTCGGATCGGCCCCG...
ASV_4  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...
ASV_5  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...

In [27]:
RREAS = [otu_all,taxa_all,seq_all]

### Flyer2018 Data

In [29]:
marker = '18S'
prefix = 'Flyer2018'

# otu table
file = prefix +'_'+marker+'_otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))

# taxa table
file = prefix +'_'+marker+'_taxa_filtered.csv'
df = pd.read_csv(directory+file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
taxa_all = df.copy()
print('Number ASVs:', len(df.index))

# sequence table
file = prefix +'_'+marker+'_seq_filtered.csv'
df = pd.read_csv(directory +file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
seq_all = df.copy()
print('Number ASVs:', len(df.index))

df.head()

./Data/filtered_data/Flyer2018_18S_otu_filtered.csv
Number ASVs: 7823
Number ASVs: 7823
Number ASVs: 7823

                                                sequence
ASV
ASV_1  GCTACTACCGATTGAACATTTTAGTGAGGTCCTCGGACTGTGAGCC...
ASV_2  GCTACTACCGATTGAACGTTTTAGTGAGGTCCTCGGACTGTTTGCC...
ASV_3  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...
ASV_4  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACCTCCCCAG...
ASV_5  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...

In [30]:
Flyer = [otu_all,taxa_all,seq_all]

## Merge by unique ASV sequence

### Create dataframe that is indexed by sequence

In [36]:
levels = list(Flyer[1])
print(levels)
#df = Flyer[0].copy()
df = pd.concat([Flyer[0], Flyer[1], Flyer[2]], axis=1)
df = df.reset_index()
df.set_index('sequence', inplace=True)
Flyer_merged = df.copy()
Flyer_merged.head()

['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

,ASV,CN18Sc09_2_eDNA_Z,CN18Sc10_2_eDNA_Z,CN18Sc14_2_eDNA_Z,CN18Sc14_8_eDNA_Z,CN18Sc15_2_eDNA_Z,CN18Sc15_8_eDNA_Z,CN18Sc18_2_eDNA_Z,CN18Sc18_8_eDNA_Z,CN18Sc27_2_eDNA_Z,...,CN18FESPkoa_SC29_CC,CN18FESPkoa_SC26_CC,CN18FESPkoa_SC24_CC,Kingdom,Phylum,Class,Order,Family,Genus,Species
sequence,,,,,,,,,,,,,,,,,,,,,
GCTACTACCGATTGAACATTTTAGTGAGGTCCTCGGACTGTGAGCCAGGCGGGTCGCCCTGCCTGGTCTACGGGAAGACGACCAAACTGTAGTGTTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCC,ASV_1,0,0,2,2,3,3191,1,0,1,...,2,68,78,Eukaryota,Arthropoda,Hexanauplia,Calanoida,Paracalanidae,Paracalanus,unassigned
GCTACTACCGATTGAACGTTTTAGTGAGGTCCTCGGACTGTTTGCCTGGCGGATTACTCTGCCTGGCTGGCGGGAAGACGACCAAACTGTAGCGTTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCC,ASV_2,2,1,4,1,2,0,3,0,1,...,2,0,37,Eukaryota,Arthropoda,Hexanauplia,Calanoida,Calanidae,unassigned,unassigned
GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAGTGTTCAGTTCCTGAACGTTGCAGTGGAAAGTTTAGTGAACCTTATCACTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCC,ASV_3,388,303,428,504,221,874,398,116,320,...,258,21,393,Eukaryota,unknown,Dinophyceae,Thoracosphaerales,Thoracosphaeraceae,Ensiculifera,Ensiculifera imariensis
GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACCTCCCCAGGGCCCAGTTACTGTGTGCTGGGGAGGAAAGTTTAGTGAACCTTATCACTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCC,ASV_4,0,0,0,0,0,1,0,4,0,...,7,16,13,Eukaryota,unknown,Dinophyceae,Gymnodiniales,Gymnodiniaceae,Akashiwo,Akashiwo sanguinea
GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAGTGTTCAGTTCCTGAACGTTGCAGCGGAAAGTTTAGTGAACCTTATCACTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCC,ASV_5,504,411,411,1158,407,1176,759,733,501,...,2657,932,9712,Eukaryota,unknown,Dinophyceae,unassigned,unassigned,unassigned,unassigned

In [37]:
levels = list(RREAS[1])
print(levels)
#df = Flyer[0].copy()
df = pd.concat([RREAS[0], RREAS[1], RREAS[2]], axis=1)
df = df.reset_index()
df.set_index('sequence', inplace=True)
RREAS_merged = df.copy()
RREAS_merged.head()

['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

,ASV,Lasker18Sc122_3_D0052_UU,Lasker18Sc122_5_D0053_UU,Lasker18Sc122_17_D0057_UU,Lasker18Sc122_19_D0058_UU,Lasker18Sc123_3_D0063_UU,Lasker18Sc123_5_D0064_UU,Lasker18Sc123_17_D0068_UU,Lasker18Sc123_19_D0069_UU,Lasker18Sc124_3_D0073_UU,...,Lasker18Sc158_5_D0271_UU,Lasker18Sc158_17_D0275_UU,Lasker18Sc158_19_D0276_UU,Kingdom,Phylum,Class,Order,Family,Genus,Species
sequence,,,,,,,,,,,,,,,,,,,,,
GCTACTACCGATTGAACATTTTAGTGAGGTCCTCGGACTGTGAGCCAGGCGGGTCGCCCTGCCTGGTCTACGGGAAGACGACCAAACTGTAGTGTTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCC,ASV_1,86,37,264,5373,207,89,3091,5536,151,...,98,2114,5538,Eukaryota,Arthropoda,Hexanauplia,Calanoida,Paracalanidae,Paracalanus,unassigned
GCTACTACCGATTGAACGTTTTAGTGAGGTCCTCGGACTGTTTGCCTGGCGGATTACTCTGCCTGGCTGGCGGGAAGACGACCAAACTGTAGCGTTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCC,ASV_2,9,10,22,47,55,56,33942,66375,69,...,10,9617,56,Eukaryota,Arthropoda,Hexanauplia,Calanoida,Calanidae,unassigned,unassigned
GCTACTACCGATTGGATGGTTTAGTGAGGTCCTCGGATCGGCCCCGCCGGGGCTCCTCGCGGGCCCTGGCGGAGCGCCGAGAAGACGATCAAACTTGACTATCTAGAGGAAGTAAAAGTCGTAACAAGGTTTCC,ASV_3,0,0,0,0,0,0,0,0,0,...,16,0,0,Eukaryota,Chordata,Actinopteri,unassigned,unassigned,unassigned,unassigned
GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAGTGTTCAGTTCCTGAACGTTGCAGTGGAAAGTTTAGTGAACCTTATCACTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCC,ASV_4,1505,1333,805,736,1110,889,4023,9818,454,...,1402,12076,6361,Eukaryota,unknown,Dinophyceae,Thoracosphaerales,Thoracosphaeraceae,Ensiculifera,Ensiculifera imariensis
GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAGTGTTCAGTTCCTGAACGTTGCAGCGGAAAGTTTAGTGAACCTTATCACTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCC,ASV_5,2196,1663,830,981,2369,2096,64,102,2718,...,4062,1402,837,Eukaryota,unknown,Dinophyceae,unassigned,unassigned,unassigned,unassigned

## Join by sequence

In [61]:
df = pd.concat([Flyer_merged, RREAS_merged], axis=0)
taxa_df = df[levels]  #save taxonomy info by sequence
df = df.reset_index()
print(len(df.index))
'''#check for identical sequences
df['DUP'] = df.duplicated('sequence')
df = df.loc[df['DUP']==True]'''

#group by identical sequence and sum (lose categorical data)
df = df.groupby('sequence').sum()
print(len(df.index))
#get new ASV IDs, order by total abundance
df['tot'] = df.sum(axis=1)
df= df.sort_values('tot', ascending=False)
#for now keep in single-read ASVs
df = df.reset_index()
df['ASV'] = df.index +1
df['ASV'] = 'ASV_' + df['ASV'].astype(str)
#get taxonomy back
df.set_index('sequence',inplace=True)
#for now, just drop taxonomy of duplicate sequences (take first)
df = pd.concat([taxa_df.reset_index().drop_duplicates('sequence').set_index('sequence'), df], axis=1)
df= df.sort_values('tot', ascending=False)
df.drop('tot', axis=1, inplace=True)
df.reset_index(inplace=True)
df.set_index('ASV',inplace=True)
seq_project = df[['sequence']]
taxa_project = df[levels]
df = df.drop(levels, axis=1)
df = df.drop(['sequence'], axis=1)
otu_project = df.copy()

15320
10614

/var/folders/5v/h4s_0pz17yb6f6krsxkzr5dw000b65/T/ipykernel_22194/4027020074.py:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = df.groupby('sequence').sum()

In [62]:
# merge metadata files later?

### Save Files

In [64]:
plot_dir = './Data/merged_data/'

In [65]:
#export to csv files for R plotting
dfs = [otu_project, taxa_project, seq_project]
names = ['otu', 'taxa', 'seq']
for df, name in zip(dfs,names):
    df.to_csv(plot_dir + 'Merged_'+marker+'_'+name+'_filtered.csv')
    print(plot_dir + 'Merged_'+marker+'_'+name+'_filtered.csv')
df.head()

./Data/merged_data/Merged_18S_otu_filtered.csv
./Data/merged_data/Merged_18S_taxa_filtered.csv
./Data/merged_data/Merged_18S_seq_filtered.csv

                                                sequence
ASV
ASV_1  GCTACTACCGATTGAACGTTTTAGTGAGGTCCTCGGACTGTTTGCC...
ASV_2  GCTACTACCGATTGAACGTTTTAGTGAGGTCCACGGACTGTTTGCA...
ASV_3  GCTACTACCGATTGAACATTTTAGTGAGGTCCTCGGACTGTGAGCC...
ASV_4  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...
ASV_5  GCTCCTACCGATTGAGTGATCCGGTGAATAATTCGGACTGCAGCAG...

# COI data

### RREAS2018

In [66]:
marker = 'COI'
prefix = 'RREAS2018'

# otu table
file = prefix +'_'+marker+'_otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))

# taxa table
file = prefix +'_'+marker+'_taxa_filtered.csv'
df = pd.read_csv(directory+file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
taxa_all = df.copy()
print('Number ASVs:', len(df.index))

# sequence table
file = prefix +'_'+marker+'_seq_filtered.csv'
df = pd.read_csv(directory +file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
seq_all = df.copy()
print('Number ASVs:', len(df.index))

df.head()

./Data/filtered_data/RREAS2018_COI_otu_filtered.csv
Number ASVs: 9378
Number ASVs: 9378
Number ASVs: 9378

                                                sequence
ASV
ASV_1  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_2  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_3  TTAAGAATAAATATCGCCCATTCAGGCCCATCTGTCGATTTTGCTA...
ASV_4  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_5  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...

In [67]:
RREAS = [otu_all,taxa_all,seq_all]

### Flyer2018 Data

In [68]:
marker = 'COI'
prefix = 'Flyer2018'

# otu table
file = prefix +'_'+marker+'_otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))

# taxa table
file = prefix +'_'+marker+'_taxa_filtered.csv'
df = pd.read_csv(directory+file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
taxa_all = df.copy()
print('Number ASVs:', len(df.index))

# sequence table
file = prefix +'_'+marker+'_seq_filtered.csv'
df = pd.read_csv(directory +file)
df = df.rename(columns= {'Unnamed: 0': 'ASV'})
df.set_index('ASV', inplace=True)
seq_all = df.copy()
print('Number ASVs:', len(df.index))

df.head()

./Data/filtered_data/Flyer2018_COI_otu_filtered.csv
Number ASVs: 12709
Number ASVs: 12709
Number ASVs: 12709

                                                sequence
ASV
ASV_1  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_2  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_3  TTAAGAATAAATATCGCCCATTCAGGCCCATCTGTCGATTTTGCTA...
ASV_4  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_5  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...

In [69]:
Flyer = [otu_all,taxa_all,seq_all]

## Merge by unique ASV sequence

### Create dataframe that is indexed by sequence

In [70]:
levels = list(Flyer[1])
print(levels)
#df = Flyer[0].copy()
df = pd.concat([Flyer[0], Flyer[1], Flyer[2]], axis=1)
df = df.reset_index()
df.set_index('sequence', inplace=True)
Flyer_merged = df.copy()
Flyer_merged.head()

['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

,ASV,CN18FESPkoa_SC58_FF,CN18FESPkoa_SC57_FF,CN18FESPkoa_SC56_FF,CN18FESPkoa_SC55_FF,CN18FESPkoa_SC53_FF,CN18FESPkoa_SC52_FF,CN18FESPkoa_SC49_FF,CN18FESPkoa_SC47_FF,CN18FESPkoa_SC46_FF,...,CN18SESPkoa_SC39_Y,CN18SESPkoa_SC37_Y,CN18SESPkoa_SC36_Y,Kingdom,Phylum,Class,Order,Family,Genus,Species
sequence,,,,,,,,,,,,,,,,,,,,,
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTATATCAACATT,ASV_1,2459,1530,1718,1046,2579,900,2311,2244,1459,...,1984,136,2521,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAATATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTGTATCAACACT,ASV_2,2756,2283,2782,1407,3372,1855,1877,1831,1933,...,305,9,322,Eukaryota,Haptista,Haptophyta,Isochrysidales,Noelaerhabdaceae,Emiliania,Emiliania huxleyi
TTAAGAATAAATATCGCCCATTCAGGCCCATCTGTCGATTTTGCTATCTTTTCTCTACACCTAGCCGGAGTCTCATCCCTTTTAGGGGCAGTGAATTTTATTAGGACTTTTGGGAATTTACGAAGATTTGGTATTCAGTTAGACCGTACTCCTTTATTTGGATGATCGGTTTTAATTACAACTATTTTACTTCTTCTCTCTCTACCTGTCCTAGCAGGGGCTATTACCATGCTTTTAACAGACCGAAACTTAAATACTTCATTTTATGACTCAGGGGGTGGTGGAGATCCTATTTTATACCAACACT,ASV_3,11854,13699,6132,5487,35332,19366,19192,7070,4154,...,0,11,2958,Eukaryota,Arthropoda,Hexanauplia,Poecilostomatoida,Oncaeidae,g_,s_
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTGTATCAACACT,ASV_4,0,0,0,0,0,1,3,1,0,...,399,4,617,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGATCCAGTATTGTATCAACACT,ASV_5,1607,1609,2094,870,2101,644,1935,1420,1517,...,1078,12,2397,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned

In [71]:
levels = list(RREAS[1])
print(levels)
#df = Flyer[0].copy()
df = pd.concat([RREAS[0], RREAS[1], RREAS[2]], axis=1)
df = df.reset_index()
df.set_index('sequence', inplace=True)
RREAS_merged = df.copy()
RREAS_merged.head()

['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

,ASV,Lasker18Sc122_3_D0052,Lasker18Sc122_5_D0053,Lasker18Sc122_17_D0057,Lasker18Sc122_19_D0058,Lasker18Sc123_3_D0063,Lasker18Sc123_5_D0064,Lasker18Sc123_17_D0068,Lasker18Sc123_19_D0069,Lasker18Sc124_3_D0073,...,Lasker18Sc158_5_D0271,Lasker18Sc158_17_D0275,Lasker18Sc158_19_D0276,Kingdom,Phylum,Class,Order,Family,Genus,Species
sequence,,,,,,,,,,,,,,,,,,,,,
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTATATCAACATT,ASV_1,3647,6747,10464,9959,274,665,1168,673,346,...,559,593,605,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAATATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTGTATCAACACT,ASV_2,1032,1461,753,886,984,1770,2764,1387,276,...,146,290,301,Eukaryota,Haptista,Haptophyta,Isochrysidales,Noelaerhabdaceae,Emiliania,Emiliania huxleyi
TTAAGAATAAATATCGCCCATTCAGGCCCATCTGTCGATTTTGCTATCTTTTCTCTACACCTAGCCGGAGTCTCATCCCTTTTAGGGGCAGTGAATTTTATTAGGACTTTTGGGAATTTACGAAGATTTGGTATTCAGTTAGACCGTACTCCTTTATTTGGATGATCGGTTTTAATTACAACTATTTTACTTCTTCTCTCTCTACCTGTCCTAGCAGGGGCTATTACCATGCTTTTAACAGACCGAAACTTAAATACTTCATTTTATGACTCAGGGGGTGGTGGAGATCCTATTTTATACCAACACT,ASV_3,2347,3,2206,0,1630,2233,1,3117,5,...,4709,1,1,Eukaryota,Arthropoda,Hexanauplia,Poecilostomatoida,Oncaeidae,g_,s_
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGACCCAGTATTGTATCAACACT,ASV_4,3682,5423,4859,3678,502,1038,3170,1522,322,...,194,161,103,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned
TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCAATTTTCTCTCTTCATTTAGCCGGAGTTTCGTCGATTCTTGGTGCAATTAATTTTATTGTAACAATTATGAACATGCGAGCTCCAGGAATGACTGCTCACCGAACTCCTTTATTTGTATGAGCTGTATTTATTACAGCTTTCTTACTTTTATTGTCTTTACCGGTTCTAGCAGGAGCTATTACAATGCTTTTAACAGATCGTAACTTTAATACGTCATTCTTCGACCCTAATGGTGGAGGTGATCCAGTATTGTATCAACACT,ASV_5,1340,2104,1875,1365,1785,3468,9147,6836,124,...,494,625,409,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned

## Join by sequence

In [72]:
df = pd.concat([Flyer_merged, RREAS_merged], axis=0)
taxa_df = df[levels]  #save taxonomy info by sequence
df = df.reset_index()
print(len(df.index))
'''#check for identical sequences
df['DUP'] = df.duplicated('sequence')
df = df.loc[df['DUP']==True]'''

#group by identical sequence and sum (lose categorical data)
df = df.groupby('sequence').sum()
print(len(df.index))
#get new ASV IDs, order by total abundance
df['tot'] = df.sum(axis=1)
df= df.sort_values('tot', ascending=False)
#for now keep in single-read ASVs
df = df.reset_index()
df['ASV'] = df.index +1
df['ASV'] = 'ASV_' + df['ASV'].astype(str)
#get taxonomy back
df.set_index('sequence',inplace=True)
#for now, just drop taxonomy of duplicate sequences (take first)
df = pd.concat([taxa_df.reset_index().drop_duplicates('sequence').set_index('sequence'), df], axis=1)
df= df.sort_values('tot', ascending=False)
df.drop('tot', axis=1, inplace=True)
df.reset_index(inplace=True)
df.set_index('ASV',inplace=True)
seq_project = df[['sequence']]
taxa_project = df[levels]
df = df.drop(levels, axis=1)
df = df.drop(['sequence'], axis=1)
otu_project = df.copy()

22087
18035

/var/folders/5v/h4s_0pz17yb6f6krsxkzr5dw000b65/T/ipykernel_22194/4027020074.py:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = df.groupby('sequence').sum()

In [73]:
# merge metadata files later?

### Save Files

In [74]:
plot_dir = './Data/merged_data/'

In [75]:
#export to csv files for R plotting
dfs = [otu_project, taxa_project, seq_project]
names = ['otu', 'taxa', 'seq']
for df, name in zip(dfs,names):
    df.to_csv(plot_dir + 'Merged_'+marker+'_'+name+'_filtered.csv')
    print(plot_dir + 'Merged_'+marker+'_'+name+'_filtered.csv')
df.head()

./Data/merged_data/Merged_COI_otu_filtered.csv
./Data/merged_data/Merged_COI_taxa_filtered.csv
./Data/merged_data/Merged_COI_seq_filtered.csv

                                                sequence
ASV
ASV_1  TTAAGAATAAATATCGCCCATTCAGGCCCATCTGTCGATTTTGCTA...
ASV_2  GTTAAGAAGAAACATTGCCCATGGGGGTGCATCTGTAGATCTCGCT...
ASV_3  TCTAGCAGGGATTCAAGCTCATTCAGGAGGTTCTGTTGATTTAGCA...
ASV_4  TTTATCGAGTATTCAGGCACATTCAGGTCCTTCGGTTGATTTAGCT...
ASV_5  ATTAGCAAGTATTGCTTTCCATTCAGGAGGAGCGGTTGATTGTGCA...