# Merge Amplicon Datasets by ASV sequence

Join "Flyer2018" and "RREAS2018" datasets for 18S, COI, and 12S

In [3]:
import pandas as pd
# import glob

### Set Locations

In [7]:
directory = "./Data/"
markers = ['18S', 'COI', '12S']
# prefixes = ['RREAS2018', 'Flyer2018']

## Import Data

### RREAS2018

In [10]:
marker = '18S'
prefix = 'RREAS2018'

# otu table
file = prefix +'_'+marker+'_otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
#df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))
df

./Data/RREAS2018_18S_otu_filtered.csv
Number ASVs: 7497

,Unnamed: 0,Lasker18Sc122_3_D0052_UU,Lasker18Sc122_5_D0053_UU,Lasker18Sc122_17_D0057_UU,Lasker18Sc122_19_D0058_UU,Lasker18Sc123_3_D0063_UU,Lasker18Sc123_5_D0064_UU,Lasker18Sc123_17_D0068_UU,Lasker18Sc123_19_D0069_UU,Lasker18Sc124_3_D0073_UU,...,Lasker18Sc153_17_D0255_UU,Lasker18Sc153_19_D0256_UU,Lasker18Sc154_3_D0260_UU,Lasker18Sc154_5_D0261_UU,Lasker18Sc154_17_D0265_UU,Lasker18Sc154_19_D0266_UU,Lasker18Sc158_3_D0270_UU,Lasker18Sc158_5_D0271_UU,Lasker18Sc158_17_D0275_UU,Lasker18Sc158_19_D0276_UU
0,ASV_1,86,37,264,5373,207,89,3091,5536,151,...,5751,1311,142,70,2569,2881,154,98,2114,5538
1,ASV_2,9,10,22,47,55,56,33942,66375,69,...,38704,12263,38,32,88,33,14,10,9617,56
2,ASV_3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,28,16,0,0
3,ASV_4,1505,1333,805,736,1110,889,4023,9818,454,...,4081,5577,676,791,10199,8836,852,1402,12076,6361
4,ASV_5,2196,1663,830,981,2369,2096,64,102,2718,...,325,124,1794,1612,412,495,2954,4062,1402,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7492,ASV_50641,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
7493,ASV_50677,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7494,ASV_50709,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7495,ASV_50837,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,ASV_50872,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
marker = '18S'
prefix = 'RREAS2018'

# otu table
file = prefix +'_'+marker+'otu_filtered.csv'
print(directory+file)
df = pd.read_csv(directory + file)
df.set_index('ASV', inplace=True)
otu_all = df.copy()
print('Number ASVs:', len(df.index))

# taxa table
file = 'Collapsed_taxa_table_unfiltered.csv'
df = pd.read_csv(directory+file)
df.set_index('ASV', inplace=True)
taxa_all = df.copy()
print('Number ASVs:', len(df.index))

# metadata
file = 'Collapsed_meta_table_unfiltered.csv'
df = pd.read_csv(directory+file)
df.set_index('sample_name', inplace=True)
meta_all = df.copy()
print('Number samples:', len(df.index))

# sequence table
file = 'Collapsed_seq_table_unfiltered.csv'
df = pd.read_csv(directory +file)
df.set_index('ASV', inplace=True)
seq_all = df.copy()
print('Number ASVs:', len(df.index))